import esbuild from 'esbuild'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Build configuration for bundling the CLI with workspace dependencies
const buildConfig = {
	entryPoints: ['src/index.ts'],
	bundle: true,
	platform: 'node',
	target: 'node20',
	format: 'esm',
	outfile: 'dist/index.js',
	banner: {
		js: `import { createRequire as __createRequire__ } from 'module';
import { fileURLToPath as __fileURLToPath__ } from 'url';
import { dirname as __dirname__ } from 'path';
const require = __createRequire__(import.meta.url);
const __filename = __fileURLToPath__(import.meta.url);
const __dirname = __dirname__(__filename);
`,
	},
	external: [
		// Keep these as external dependencies (will be installed via npm)
		'@anthropic-ai/bedrock-sdk',
		'@anthropic-ai/sdk',
		'@anthropic-ai/vertex-sdk',
		'@aws-sdk/client-bedrock-runtime',
		'@aws-sdk/credential-providers',
		'@cerebras/cerebras_cloud_sdk',
		'@google/genai',
		'@lmstudio/sdk',
		'@mistralai/mistralai',
		'@modelcontextprotocol/sdk',
		'@qdrant/js-client-rest',
		'@vscode/codicons',
		'@vscode/ripgrep',
		'async-mutex',
		'axios',
		'chalk',
		'cheerio',
		'chokidar',
		'clone-deep',
		'commander',
		'default-shell',
		'delay',
		'diff',
		'diff-match-patch',
		'dotenv',
		'eventemitter3',
		'exceljs',
		'fast-deep-equal',
		'fast-xml-parser',
		'fastest-levenshtein',
		'fs-extra',
		'fuse.js',
		'fzf',
		'get-folder-size',
		'google-auth-library',
		'gray-matter',
		'i18next',
		'ignore',
		'ink',
		'ink-big-text',
		'ink-gradient',
		'ink-select-input',
		'ink-spinner',
		'ink-table',
		'ink-text-input',
		'is-wsl',
		'isbinaryfile',
		'jotai',
		'jsdom',
		'json5',
		'jwt-decode',
		'lodash.debounce',
		'lru-cache',
		'mammoth',
		'monaco-vscode-textmate-theme-converter',
		'node-cache',
		'node-ipc',
		'ollama',
		'openai',
		'os-name',
		'p-limit',
		'p-wait-for',
		'pdf-parse',
		'pkce-challenge',
		'pretty-bytes',
		'proper-lockfile',
		'ps-tree',
		'puppeteer-chromium-resolver',
		'puppeteer-core',
		'react',
		'reconnecting-eventsource',
		'sanitize-filename',
		'say',
		'serialize-error',
		'shiki',
		'simple-git',
		'socket.io-client',
		'sound-play',
		'stream-json',
		'string-similarity',
		'strip-ansi',
		'strip-bom',
		'tiktoken',
		'tmp',
		'tree-sitter-wasms',
		'ts-node',
		'turndown',
		'undici',
		'uri-js',
		'uuid',
		'vscode-material-icons',
		'vscode-uri',
		'web-tree-sitter',
		'workerpool',
		'yaml',
		'zod',
	],
	// Bundle workspace dependencies (@roo-code/*)
	// These will be included in the bundle
	sourcemap: false,
	minify: false,
	treeShaking: true,
	logLevel: 'info',
}

// Build the CLI
esbuild.build(buildConfig).catch(() => process.exit(1))