// kilocode_change - new file: Language mapping constants for SVG syntax highlighting
export const VS_CODE_TO_SHIKI_LANGUAGE_MAP: Record<string, string> = {
	typescript: "typescript",
	javascript: "javascript",
	typescriptreact: "typescript",
	javascriptreact: "javascript",
	python: "python",
	java: "java",
	cpp: "cpp",
	c: "c",
	csharp: "csharp",
	go: "go",
	rust: "rust",
	php: "php",
	ruby: "ruby",
	swift: "swift",
	kotlin: "kotlin",
	scala: "scala",
	html: "html",
	css: "css",
	json: "json",
	jsonc: "json",
	yaml: "yaml",
	yml: "yaml",
	xml: "xml",
	markdown: "markdown",
	shellscript: "bash",
	bash: "bash",
	sh: "shell",
	sql: "sql",
	dockerfile: "dockerfile",
	plaintext: "plaintext",
}
